### ISSUE TITLE
[UI] As a user, I can see the More Products Type section in Product Details screen

### ISSUE THREAD

**Issue by minhnimble** [minhnimble/nimble-ecommerce-planning#45]
## Description
The users will be able to see `More Products Type` section below the `Size` section in Discover screen.

## Acceptance Criteria
- [ ] Reuse the container table view from this task #41.
- [ ] Reuse the table view header from this task #42.
- [ ] Update a header title on the left with text: `More {product_type}`.
- [ ] Add a new header button to the right with text: `Shop all`.
- [ ] Create a horizontal table view for this section.
- [ ] Reuse the table view item UI layout from this task: #11.

## Design
- Figma design: [Product Details screen](https://www.figma.com/proto/GXmbnWUEH9ZkrUluaPyedn/e-commerce?node-id=41%3A523&amp%3Bviewport=1944%2C-468%2C1.197691559791565&amp%3Bscaling=scale-down&scaling=min-zoom)

- UI screenshot:
<img width="339" alt="Screen Shot 2021-07-15 at 11 21 08" src="https://user-images.githubusercontent.com/70877098/125730445-b65dcbb2-419f-4dee-8763-e10f11bd7a44.png">
